# Generated by Django 4.1.3 on 2022-12-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GArchivage', '0002_etatcivil_numero_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatcivil',
            name='dossier',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
